### ISSUE TITLE
Rechnungsdatum

### ISSUE THREAD

**Issue by moritzgloeckl** [sveneusewig/gnucash-german-taxinvoice#3]
Eventuell wäre es sinnvoll, zum Beispiel unter der Rechnungsnummer noch ein Rechnungsdatum hinzuzufügen. Ich denke, dass das Erstelldatum der Rechnung wichtig ist und ggf. von den Aufträgen abweichen kann.

Nachtrag: Eventuell doch nicht zwingend notwendig da je nach Rechnungsstatus schon angezeigt wird.

**Comment by sveneusewig** [comment]
Das tut es schon.
